[build]
  functions = "build" # Build directory for lambda functions
  command = "npm run build"

# Different environments based on context
# On production, devDependencies will not be installed
[build.environment]
  NODE_ENV = "development"
[context.production.environment]
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

    Content-Security-Policy = "upgrade-insecure-requests; block-all-mixed-content;"
    Feature-Policy = "vibrate 'none'; geolocation 'none'; microphone 'none'; camera 'none'"
    Referrer-Policy = "no-referrer"
